# # CI
# FROM node:18.17.0 as build
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . ./
# RUN npm run build:production


# Ansible
FROM nginx:1.25.4-alpine
COPY nginx.default.conf.template /etc/nginx/templates/default.conf.template
EXPOSE 4200
COPY /var/www/html/dist/frontend/browser /usr/share/nginx/html/frontend
