FROM nginx:1.25.4-alpine

RUN ls -la

COPY certificat/ /etc/nginx/certificat/
COPY nginx.frontend.conf /etc/nginx/templates/default.conf.template
COPY dist/frontend/browser /usr/share/nginx/html/frontend
