version: '3.9'
services:
  frontend:
    restart: always
    volumes:
      - ./etc/letsencrypt/live/greglmx.com/fullchain.pem:/etc/letsencrypt/live/greglmx.com/fullchain.pem
      - ./etc/letsencrypt/live/greglmx.com/privkey.pem:/etc/letsencrypt/live/greglmx.com/privkey.pem
    build:
      dockerfile: Dockerfile.frontend.prod
    ports:
      - '80:80'
      - '443:443'
    expose:
      - 80
      - 443

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
      - mysql-phpmyadmin
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 2s
      retries: 20
      start_period: 10s

  backend:
    restart: always
    build:
      dockerfile: Dockerfile.backend.prod
    ports:
      - '5000:5000'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - MPABOX_API_URL=${MPABOX_API_URL}
      - MAPBOX_SESSION_TOKEN=${MAPBOX_SESSION_TOKEN}
      - TICKETMASTER_API_URL=${TICKETMASTER_API_URL}
      - TICKETMASTER_ACCESS_TOKEN=${TICKETMASTER_ACCESS_TOKEN}
      - FOURSQUARE_API_URL=${FOURSQUARE_API_URL}
      - FOURSQUARE_API_KEY=${FOURSQUARE_API_KEY}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - 8080:80
    networks:
      - mysql-phpmyadmin

networks:
  backend:
    driver: bridge
  mysql-phpmyadmin:
    driver: bridge

volumes:
  dbdata:
