name: Build and Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/build_and_deploy_frontend.yml

jobs:
  build:
    uses: ./.github/workflows/build_frontend.yml
    # with:
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy_frontend.yml
    # with:
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
