name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths:
    #   - frontend/**

jobs:
  build:
    env:
      MAPBOX_ACCES_TOKEN: ${{ secrets.MAPBOX_ACCES_TOKEN }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Run build project
        run: npm run build:production

    # - name: Setup Ansible
    #   run:

    # - name: Deploy with Ansible in to Server VPS
    #   run:
