# this github workflow is called in the main workflow file to build and deploy the frontend application

name: Deploy All CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Build environment variables
        run: npm run build:production:env

      - name: Run build project
        run: npm run build:production

      - name: deploy angular app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "./frontend/dist/*, ./frontend/Dockerfile.frontend.prod, ./frontend/nginx.default.conf.template, ./prod/docker-compose.yml"
          target: "/var/www/html"
          strip_components: 1
          overwrite: true
          # rm: true
