name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/build_and_deploy_backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Compose service images
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          MPABOX_API_URL: ${{ secrets.MPABOX_API_URL }}
          MAPBOX_SESSION_TOKEN: ${{ secrets.MAPBOX_SESSION_TOKEN }}
          TICKETMASTER_API_URL: ${{ secrets.TICKETMASTER_API_URL }}
          TICKETMASTER_ACCESS_TOKEN: ${{ secrets.TICKETMASTER_ACCESS_TOKEN }}
        run: cd prod && docker compose build

      - name: copy backend flask app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "./backend/*, ./backend/Dockerfile.backend.prod, ./prod/docker-compose.yml, !./backend/Dockerfile"
          target: "/var/www/html/backend"
          strip_components: 1
          overwrite: true
          # rm: true

      - name: Deploy Backend with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |

            # Déplacer les fichiers nécessaires
            cd /var/www/html
            mv backend/prod/* . # docker-compose.yml
            mv backend/backend/* . # Dockerfile.backend.prod
            rm -rf backend/prod backend/backend

            # Vérifier si le conteneur de la base de données est prêt
            # echo "Waiting for database container to be ready..."
            # while ! docker compose exec -T db mysqladmin ping --silent; do
            #     sleep 1
            # done

            # Relancer les conteneurs avec Docker Compose
            echo "Starting backend deployment..."
            docker compose restart backend
            echo "Backend deployment completed."
