name: Build and Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/build_and_deploy_frontend.yml

jobs:
  build:
    uses: ./.github/workflows/build_frontend.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy_frontend.yml
