name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/build_and_deploy_backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: copy backend flask app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "./backend/*, ./frontend/Dockerfile.backend.prod, ./prod/docker-compose.yml"
          target: "/var/www/html"
          strip_components: 1
          overwrite: true
          # rm: true

      - name: Deploy Backend with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Définir les variables
            APP_DIR="/backend"

            # Déplacer les fichiers nécessaires
            cd /var/www/html
            mv backend/* .
            mv prod/* .
            rm -rf backend prod

            # Vérifier si le conteneur de la base de données est prêt
            echo "Waiting for database container to be ready..."
            while ! docker compose exec -T db mysqladmin ping --silent; do
                sleep 1
            done

            # Relancer les conteneurs avec Docker Compose
            docker compose down backend
            docker compose up --build -d backend

            echo "Backend deployment completed."
