name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build:
    env:
      MAPBOX_ACCES_TOKEN: ${{ secrets.MAPBOX_ACCES_TOKEN }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Run build project
        run: npm run build:production

      - name: log files
        run: ls -la ./dist/

      - name: chmod add permission
        run: chmod -R 777 ./../frontend/dist/*

      - name: log files
        run: ls -la ./dist/

      - name: deploy angular app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "./frontend/dist/*, ./frontend/Dockerfile.prod, ./frontend/nginx.default.conf.template"
          target: "/var/www/html"
          strip_components: 1
          overwrite: true
          rm: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/html
            docker-compose down
            docker-compose up --build -d frontend
