name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/build_and_deploy_backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: copy backend flask app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "./backend/*, ./backend/Dockerfile.backend.prod, ./prod/docker-compose.yml, !./backend/Dockerfile, !./backend/static/*"
          target: "/var/www/html/backend"
          strip_components: 1
          overwrite: true
          # rm: true

      - name: Deploy Backend with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |

            # Déplacer les fichiers nécessaires
            cd /var/www/html
            mv prod/* .
            rm -rf prod

            # Vérifier si le conteneur de la base de données est prêt
            # echo "Waiting for database container to be ready..."
            # while ! docker compose exec -T db mysqladmin ping --silent; do
            #     sleep 1
            # done

            # Relancer les conteneurs avec Docker Compose
            echo "Starting backend deployment..."
            docker compose down backend db phpmyadmin
            docker compose up --build -d backend db phpmyadmin

            echo "Backend deployment completed."
